apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::912901011909:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-UHWYLGZSL6CL
      username: system:node:{{EC2PrivateDNSName}}
      - groups:
        - system:masters
        rolearn: arn:aws:iam::912901011909:role/UdacityFlaskDeployCBKubectlRole
        username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-25T17:58:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1515"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 4e36c63b-38c9-4b6e-aad8-c9ad7f317099
