apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::912901011909:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-UHWYLGZSL6CL
      username: system:node:{{EC2PrivateDNSName}}
      - groups:
        - system:masters
        rolearn: arn:aws:iam::912901011909:role/UdacityFlaskDeployCBKubectlRole
        username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-25T14:25:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1488"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 7b043914-8ab5-4973-96ff-e240c04f35c0
